name: dev 
on: 
 push:
    branches: main
jobs: 
    hello:
     runs-on: ubuntu-latest
     steps:
       - name: git repo clone
         run: https://github.com/TirthMesariya/JDBC_And_Flyway.git
         

