name: dev 
on: 
 push:
    branches: main
jobs: 
    hello:
     runs-on: ubuntu-latest
     steps:
       - name: Clone Repository
         run: git clone https://github.com/TirthMesariya/JDBC_And_Flyway.git
       - name: Build and run services using Docker Compose
         run: docker compose -f docker-compose.yml up -d --build
