name: dev1

on: 
  push:
    branches: [main]

jobs: 
  hello:
    runs-on: self-hosted

    steps:
      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            curl \
            gnupg \
            lsb-release
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

          sudo usermod -aG docker $USER
          newgrp docker

      - name: Clone Repository from
        run: git clone https://github.com/TirthMesariya/JDBC_And_Flyway.git

      - name: Log in to Docker Hub
        run: echo "${{ secrets.PASSWORD1 }}" | sudo docker login -u "${{ secrets.USERNAME1 }}" --password-stdin

      - name: Build and run services using Docker Compose
        run: sudo docker compose -f JDBC_And_Flyway/docker-compose.yml up -d --build
